apiVersion: batch/v1
kind: Job
metadata:
  name: azure-example
spec:
  template:
    spec:
      initContainers:
      - name: plan
        image: silviosilva/azure-example:0.1.0
        args: ["plan", "-no-color"]
        envFrom:
        - secretRef:
            name: azure-credentials
        env:
        - name: DEBUG
          value: "0"
      - name: apply
        image: silviosilva/azure-example:0.1.0
        args: ["apply", "-auto-approve"]
        envFrom:
          - secretRef:
              name: azure-credentials
        env:
          - name: DEBUG
            value: "1"
      containers:
      - name: output
        image: silviosilva/azure-example:0.1.0
        args: ["output"]
        envFrom:
        - secretRef:
            name: azure-credentials
        env:
        - name: DEBUG
          value: "0"
      restartPolicy: Never
  backoffLimit: 4
