apiVersion: v1
kind: Pod
metadata:
  name: azure-dummy-stack
  namespace: default
spec:
  containers:
  - name: terraform
    image: silviosilva/azure-dummy-stack:latest
    args: ["plan", "-no-color"]
    env:
    - name: DEBUG
      value: "0"
    envFrom:
    - secretRef:
        name: arm-credentials
  restartPolicy: OnFailure
